language: android
jdk: oraclejdk8
sudo: false
notifications:
  email: false

android:
  components:
    - platform-tools
    - build-tools-25.0.1
    - android-22
    - sys-img-x86-android-22
    - extra-google-m2repository
licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: ./gradlew clean build
