language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - build-tools-25.0.1
    - android-25
    - sys-img-x86-android-25
    - extra-google-m2repository

script: ./gradlew clean build
