language: android

notifications:
  email: false

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build